### ISSUE TITLE
3.0.0 Pre-release check

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1130]
List of issues found using git URL import in dev branch https://www.notion.so/chainsafe/Simulating-OpenUPM-scenario-locally-16ac51527f6f4f35a73cd521472c7a50#984311877bf540e0b815fa6ba04b1210

- [ ] MUDSample scene is missing, because we don’t have samples in "mud" package  https://github.com/ChainSafe/web3.unity/issues/1136
- [ ] Providers are not added by default in a blank project, this is expected, but we need to add this to the docs, and we should add what is expected to be added by the developer in each provider
<img width="171" alt="Screenshot 2024-09-09 at 11 24 22 AM" src="https://github.com/user-attachments/assets/953105ff-7cd8-4b89-b55d-d959a63e2046">

- [x] Mint and transfer samples, are not working in web3auth, the TXs are stuck in pending: https://sepolia.etherscan.io/tx/0x8102f4d7d01b8e668d750e16cd3ba8bbb119c0378d92cc646cac7e04004fc571 and some of them are not even created apparently: https://sepolia.etherscan.io/tx/0x3f6c86f4101a0d0a9f9b552a404267c43f1a2c919cfbaff40bbcd89820e5214f  
https://github.com/ChainSafe/web3.unity/issues/1137

- [ ] In WebGL the default template is "Default" we should put "Web3.Unity" as the default template, otherwise this error appears: 
```
Invoking error handler due to
ReferenceError: web3UnityInstance is not defined
at _Connect (http://localhost:51205/Build/webgldev.framework.js.gz:30:25044)
webgldev.framework.js.gz:30 Uncaught (in promise) ReferenceError: web3UnityInstance is not defined
    at _Connect (webgldev.framework.js.gz:30:25044)
```
https://github.com/ChainSafe/web3.unity/issues/1138

- [ ] Now that we have **MarketplaceSampleScene**, shouldn't we remove this samples from "SampleMain"? https://github.com/ChainSafe/web3.unity/issues/1139

<img width="520" alt="Screenshot 2024-09-09 at 5 22 51 PM" src="https://github.com/user-attachments/assets/72e009b9-bd21-4692-bc88-eee01e41f5f9">

- [ ] Deploy Marketplace not working (thanks @JAlbertCode) https://github.com/ChainSafe/web3.unity/issues/1132

- [x] WalletConnect not working in WebGL: 
```
Invoking error handler due to
RuntimeError: null function or function signature mismatch
```
https://github.com/ChainSafe/web3.unity/issues/1140
<img width="1149" alt="Screenshot 2024-09-11 at 12 12 27 PM" src="https://github.com/user-attachments/assets/5085b000-3d62-42d9-92be-ac777f8e6e55">

- [x] Amount of ERC20 token is not displayed correctly, I added this erc20 token that i have 9837 amount, but it shows 0:
<img width="246" alt="Screenshot 2024-09-11 at 12 33 25 PM" src="https://github.com/user-attachments/assets/c5c1cee9-689c-4c37-84e6-23b93e1a3dd4">

https://github.com/ChainSafe/web3.unity/issues/1141

- [ ] Metamask connection in iOS build not working. I get redirected to Metamask, and a popup appears and disappears but Im not able to connect the wallet. I see this deep link generated but maybe is missing something: [Web3] Generated deep link: https://metamask.app.link/wc?uri=wc%3a5c8753645c6f2950dae3a8ad1c7ab53a8785293d34e307a524813997a85eea9d%402%3fsymKey%3dc8703d410274571cee7d18ac6be68f3da6d448c6050c878b92bb5dba819e5dcd%26relay-protocol%3dirn (this was working 1 week ago when I tested a PR in iOS) https://github.com/ChainSafe/web3.unity/issues/1142

- [x] Connect button is not clickable on the editor unless you disable "Connect On Initialize" checkbox @rob1997 is working on it https://github.com/ChainSafe/web3.unity/issues/1143
- [x] Remember me is not working, I guess is related to the previous issue? cc @rob1997  https://github.com/ChainSafe/web3.unity/issues/1144

- [ ] Ramp is not appearing after login in SampleMain https://github.com/ChainSafe/web3.unity/issues/1145
- [ ] @kantagara Countly is doing countly stuff.. I see user profiles being populated and sessions in "Incoming Data Logs" but I don't see a single event when triggering samples in SampleMain, we need to take a look

**Comment by juans-chainsafe** [comment]
I will be adding more items in the list when I found them during the testing

**Comment by juans-chainsafe** [comment]
@kantagara @rob1997 @creeppak  @sneakzttv I wasn't expecting this amount of items to fix/improve, if you need me to create individual issues let me know.

**Comment by kantagara** [comment]
Hey please create them, they'll be my top most priority!

**Comment by sneakzttv** [comment]
@juans-chainsafe add them to here please https://github.com/ChainSafe/web3.unity/issues/1009, i'm closing this as it's a duplicate tracker.
