### ISSUE TITLE
Inline code documentation

### ISSUE THREAD

**Issue by empea-careercriminal** [ChainSafe/web3.unity#661]
> “During the next sprint, the development team will focus on cleaning up and documenting the SDK codebase while enforcing rulesets for [StyleCop](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).
> 
> This will ensure the code is well-organized, comprehensively documented, and aligned with the project’s external libraries. Furthermore, the code is clear enough for the developer relations team to develop sample implementations autonomously.
> 
> Additionally, clarification will be sought from @kalambet on undocumented components in Chainsafe dot gaming, and tasks will be assigned among developers based on their expertise.
> 
> The goal is to make significant progress toward a cleaner and better-documented SDK by the sprint’s end.”

**Comment by kantagara** [comment]
Rules for writing the docsstring:
global.ruleset will enforce the stylecop rule [SA1600](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DocumentationRules.md) trough most of the code. For some service implementations, like LootboxService that only implements ILootboxService, we should just add #pragma warning disable SA1600 to the top of the .cs file. If you want to restore the rules you should do the #pragma warning restore SA1600 

Things that **must** have docsstring:
* class definition (what it is, what it does)
* public properties
* public methods
* public events and delegates

private things are **not** needed to have comments. Add them if they're essential to some of the public identifiers listed above.

- [ ] Write Docsstring for RPC folder Chainsafe.Gaming
- [ ] Write Docsstring for Web3 folder in Chainsafe.Gaming
- [ ] Write Docsstring for lootboxes, InProcessSigner, InProcessTransactionExecutor and NetCore 
- [ ] Write Docsstring for Gelato and Unity

**Comment by sneakzttv** [comment]
Complete
